baseURL = "https://anaminus.github.io/blog"
title = "Anaminus.Blog"
languageCode = "en-US"

markup.goldmark.renderer.unsafe = true
markup.highlight.noClasses = false
security.enableInlineShortcodes = true
build.noJSConfigInAssets = true

[taxonomies]
tag = 'tags'

[params]
description = "Blog posts from Anaminus"

[params.license]
name = "CC BY-SA-4.0"
url = "https://creativecommons.org/licenses/by-sa/4.0/"

[params.publication]
year = 2022
author = "Anaminus"
url = "https://anaminus.github.io/"
