baseURL = "https://anaminus.github.io/blog"
title = "Anaminus.Blog"
languageCode = "en-US"

markup.goldmark.parser.wrapStandAloneImageWithinParagraph = false
markup.goldmark.renderer.unsafe = true
markup.highlight.noClasses = false
security.enableInlineShortcodes = true
build.noJSConfigInAssets = true

[taxonomies]
tag = 'tags'

[outputs]
home = ['html', 'rss']
section = ['html', 'rss']
taxonomy = ['html']
term = ['html', 'rss']

[params]
description = "Blog from Anaminus."
pageListSize = 20
termListSize = 0
briefTimeline = 32

[params.formats]
tags = "#%s"

[params.license]
name = "CC BY-SA-4.0"
url = "https://creativecommons.org/licenses/by-sa/4.0/"

[params.publication]
year = 2022
author = "Anaminus"
url = "https://anaminus.github.io/"
